from __future__ import annotations

from app.contracts.legacy import (
    CompareNarrative,
    CompareReport,
    ConstraintPack,
    DimensionScore,
    EvidenceSpan,
    ExtractedFeature,
    ExtractedFeatureStore,
    InsightsReport,
    JudgeFeedback,
    LearningProfile,
    LogicLockResult,
    Penalty,
    ProjectAnchorRecord,
    ProjectRequirementRecord,
    ScoreHistoryEntry,
    ScoreReport,
    SubScore,
    Suggestion,
    TrendAnalysis,
    TrendPoint,
)

__all__ = [
    "CompareNarrative",
    "CompareReport",
    "ConstraintPack",
    "DimensionScore",
    "EvidenceSpan",
    "ExtractedFeature",
    "ExtractedFeatureStore",
    "InsightsReport",
    "JudgeFeedback",
    "LearningProfile",
    "LogicLockResult",
    "Penalty",
    "ProjectAnchorRecord",
    "ProjectRequirementRecord",
    "ScoreHistoryEntry",
    "ScoreReport",
    "SubScore",
    "Suggestion",
    "TrendAnalysis",
    "TrendPoint",
]
